"use client";

import { useEffect, useMemo, useState } from "react";
import { BarChart3, CheckCircle2, ClipboardCheck, Gift, Gamepad2, Loader2, LogIn, LogOut, Medal, Menu, RefreshCw, Search, ShieldCheck, Sparkles, Users, X } from "lucide-react";
import { createClient } from "@/lib/supabase";

type Row={registration_no:string;full_name:string;branch:string;points:number;games_played:number;paid:boolean};
type Win={id:string;registration_no:string;full_name:string;branch:string;reward_type:string;reward_label:string;created_at:string;claim_status:string;paid:boolean};
type Event={id:string;registration_no:string;full_name:string;branch:string;game:string;points_awarded:number;created_at:string};
type Data={registered:number;paid:number;payment_verified:number;players:number;games_played:number;total_points:number;rewards_won:number;rewards_claimed:number;pending_rewards:number;recent_winners:Win[];players_list:Row[];attendance_overview:{day:string;checked_in:number}[];recent_game_events:Event[]};

const tabs=[
  ["overview","Overview",BarChart3],["draw","Reward Draw",Gift],["winners","Recent Winners",Sparkles],["claims","Reward Claims",ClipboardCheck],["players","Players",Users],["leaderboard","Points Leaderboard",Medal],["payments","Payment Verification",CheckCircle2],["attendance","Attendance Overview",ClipboardCheck],
] as const;

export default function Admin(){
 const [data,setData]=useState<Data|null>(null),[session,setSession]=useState<any>(null),[authReady,setAuthReady]=useState(false),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[authError,setAuthError]=useState(""),[authBusy,setAuthBusy]=useState(false),[tab,setTab]=useState("overview"),[menuOpen,setMenuOpen]=useState(false),[rewardType,setRewardType]=useState("free_recharge"),[label,setLabel]=useState(""),[message,setMessage]=useState(""),[spinning,setSpinning]=useState(false),[winner,setWinner]=useState<any>(null),[search,setSearch]=useState("");
 async function load(){try{const r=await fetch("/api/admin/overview",{cache:"no-store"});const d=await r.json().catch(()=>({}));if(!r.ok){setData(null);setMessage(d.message||"You do not have permission to access this area.");return}setData(d)}catch{setMessage("Unable to load the admin dashboard.")}}
 useEffect(()=>{const supabase=createClient();supabase.auth.getSession().then(({data})=>{setSession(data.session);setAuthReady(true);if(data.session)load()});const {data:sub}=supabase.auth.onAuthStateChange((_event,s)=>{setSession(s);if(s)load();else setData(null)});return()=>sub.subscription.unsubscribe()},[]);
 async function login(e:React.FormEvent){e.preventDefault();setAuthBusy(true);setAuthError("");const {error}=await createClient().auth.signInWithPassword({email,password});if(error)setAuthError("The email or password could not be verified.");setAuthBusy(false)}
 async function logout(){await createClient().auth.signOut();location.reload()}
 async function spin(){if(spinning)return;setMessage("");setWinner(null);setSpinning(true);try{const r=await fetch("/api/admin/reward/spin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({rewardType,rewardLabel:label.trim()})});const d=await r.json();if(!r.ok||!d?.registration_no){setMessage(d.message||"We couldn't complete the draw. No reward was recorded.");return}setWinner(d);setTab("winners");await load()}catch{setMessage("We couldn't complete the draw. No reward was recorded.")}finally{setSpinning(false)}}
 async function paid(c:string,v:boolean){const r=await fetch("/api/admin/payment",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({code:c,paid:v})});const d=await r.json().catch(()=>({}));if(!r.ok)setMessage(d.message||"Payment status could not be changed.");else setMessage(v?"Payment verified successfully.":"Payment verification removed.");await load()}
 async function claim(id:string){const r=await fetch("/api/admin/reward/claim",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({winId:id})});const d=await r.json().catch(()=>({}));setMessage(d.message||"Reward updated.");await load()}
 const filtered=useMemo(()=>data?.players_list.filter(r=>[r.registration_no,r.full_name,r.branch].join(" ").toLowerCase().includes(search.toLowerCase()))||[],[data,search]);
 if(!authReady)return <Shell><Loading text="Checking admin session..."/></Shell>;
 if(!session)return <Shell><div className="mx-auto w-full max-w-md rounded-[2rem] bg-white p-7 shadow-2xl"><img src="/eyf-logo.png" alt="EYF" className="mx-auto h-24 w-24 rounded-full object-contain"/><div className="mt-5 text-center"><ShieldCheck className="mx-auto text-[#00B8E5]"/><h1 className="mt-2 text-2xl font-black text-[#003B63]">EYF Admin Control</h1><p className="mt-2 text-sm text-slate-500">Use your existing Supabase admin account. Access is checked against the existing EYF admin allowlist.</p></div><form onSubmit={login} className="mt-6"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Admin email" className="w-full rounded-xl border-2 border-slate-200 p-3 outline-none focus:border-[#00B8E5]" required/><input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password" className="mt-3 w-full rounded-xl border-2 border-slate-200 p-3 outline-none focus:border-[#00B8E5]" required/>{authError&&<p className="mt-3 rounded-xl bg-red-50 p-3 text-sm font-bold text-red-700">{authError}</p>}<button disabled={authBusy} className="mt-4 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#FFCC34] font-black text-[#003B63] disabled:opacity-60">{authBusy?<Loader2 className="animate-spin"/>:<LogIn/>} SIGN IN</button></form></div></Shell>;
 if(!data)return <Shell><div className="mx-auto max-w-xl rounded-[2rem] bg-white p-7 text-center shadow-xl"><img src="/eyf-logo.png" alt="EYF" className="mx-auto h-20 w-20 rounded-full object-contain"/><h1 className="mt-4 text-2xl font-black text-[#003B63]">Admin access unavailable</h1><p className="mt-2 text-slate-600">{message||"Loading..."}</p></div></Shell>;
 return <Shell><div className="mx-auto max-w-7xl overflow-hidden rounded-[2rem] bg-white shadow-2xl"><header className="hero relative flex items-center justify-between gap-4 p-5 text-white sm:p-6"><div className="flex items-center gap-3"><img src="/eyf-logo.png" alt="EYF logo" className="h-12 w-12 rounded-full bg-white object-contain"/><div><p className="text-[10px] font-black tracking-[.16em] text-[#FFCC34]">EYF 2026 EXPERIENCE</p><h1 className="text-2xl font-black sm:text-3xl">ADMIN DASHBOARD</h1></div></div><div className="relative"><button onClick={()=>setMenuOpen(v=>!v)} aria-label={menuOpen?"Close admin menu":"Open admin menu"} aria-expanded={menuOpen} className="rounded-xl bg-white/10 p-3 hover:bg-white/20">{menuOpen?<X size={21}/>:<Menu size={21}/>}</button>{menuOpen&&<div className="absolute right-0 top-[calc(100%+10px)] z-50 w-64 overflow-hidden rounded-2xl bg-white p-2 text-[#003B63] shadow-2xl ring-1 ring-black/5">{tabs.map(([id,name,Icon])=><button key={id} onClick={()=>{setTab(id);setMessage("");setMenuOpen(false)}} className={`mb-1 flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-black transition last:mb-0 ${tab===id?"bg-[#00B8E5] text-white":"hover:bg-slate-100"}`}><Icon size={17}/>{name}</button>)}<div className="my-2 border-t border-slate-100"/><button onClick={logout} className="flex w-full items-center gap-3 rounded-xl px-3 py-3 text-left text-sm font-black text-red-600 hover:bg-red-50"><LogOut size={17}/> Sign Out</button></div>}</div></header>
 <div><section className="min-w-0 bg-[#f4f8fb] p-4 sm:p-6">{message&&<div className="mb-4 rounded-xl bg-[#00B8E5]/10 p-3 text-sm font-bold text-[#004F82]">{message}</div>}{tab==="overview"&&<Overview data={data}/>} {tab==="draw"&&<Draw rewardType={rewardType} setRewardType={setRewardType} label={label} setLabel={setLabel} spinning={spinning} winner={winner} spin={spin}/>} {tab==="winners"&&<Winners data={data} claim={claim}/>} {tab==="claims"&&<Claims data={data} claim={claim}/>} {tab==="players"&&<Players rows={filtered} search={search} setSearch={setSearch} onPaid={paid}/>} {tab==="leaderboard"&&<Leaderboard rows={data.players_list}/>} {tab==="payments"&&<Players rows={filtered} search={search} setSearch={setSearch} onPaid={paid} paymentOnly/>} {tab==="attendance"&&<Attendance rows={data.attendance_overview}/>}</section></div></div></Shell>;
}

function Shell({children}:{children:React.ReactNode}){return <main className="min-h-screen bg-[#003B63] p-3 sm:p-6">{children}</main>}
function Loading({text}:{text:string}){return <div className="grid min-h-[70vh] place-items-center"><div className="text-center text-white"><img src="/eyf-logo.png" alt="EYF" className="mx-auto h-20 w-20 rounded-full bg-white object-contain"/><Loader2 className="mx-auto mt-4 animate-spin text-[#00B8E5]"/><p className="mt-3 font-black">{text}</p></div></div>}
function Title({title,sub}:{title:string;sub?:string}){return <div className="mb-5"><h2 className="text-2xl font-black text-[#003B63]">{title}</h2>{sub&&<p className="mt-1 text-sm text-slate-500">{sub}</p>}</div>}
function Kpi({label,value,icon}:{label:string;value:number;icon:React.ReactNode}){return <div className="rounded-2xl border border-slate-100 bg-white p-4 shadow-sm"><div className="text-[#00B8E5]">{icon}</div><p className="mt-2 text-2xl font-black text-[#003B63]">{value}</p><p className="text-xs font-bold uppercase tracking-wider text-slate-500">{label}</p></div>}
function Overview({data}:{data:Data}){return <><Title title="Overview" sub="Live figures from the existing EYF production database."/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Kpi label="Registered" value={data.registered} icon={<Users/>}/><Kpi label="Payment Verified" value={data.payment_verified} icon={<CheckCircle2/>}/><Kpi label="Total Points" value={data.total_points} icon={<Medal/>}/><Kpi label="Games Played" value={data.games_played} icon={<Gamepad2/>}/><Kpi label="Rewards Won" value={data.rewards_won} icon={<Gift/>}/></div><div className="mt-5 grid gap-5 xl:grid-cols-2"><Panel title="Recent Game Activity">{data.recent_game_events.length===0?<Empty text="No games have been recorded yet."/>:<div className="space-y-2">{data.recent_game_events.slice(0,8).map(e=><div key={e.id} className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 p-3 text-sm"><div><b className="text-[#003B63]">{e.full_name}</b><p className="text-slate-500">{e.registration_no} • {e.game.replace("_"," ")}</p></div><b className="text-[#004F82]">+{e.points_awarded}</b></div>)}</div>}</Panel><Panel title="Reward Status"><div className="grid grid-cols-3 gap-2"><Mini label="Won" value={data.rewards_won}/><Mini label="Claimed" value={data.rewards_claimed}/><Mini label="Pending" value={data.pending_rewards}/></div><p className="mt-4 text-sm text-slate-500">Previous winners remain eligible for future random draws.</p></Panel></div></>}
function Mini({label,value}:{label:string;value:number}){return <div className="rounded-xl bg-slate-50 p-3 text-center"><b className="text-xl text-[#003B63]">{value}</b><p className="text-[10px] font-black uppercase text-slate-500">{label}</p></div>}
function Panel({title,children}:{title:string;children:React.ReactNode}){return <div className="rounded-2xl bg-white p-5 shadow-sm"><h3 className="font-black text-[#003B63]">{title}</h3><div className="mt-4">{children}</div></div>}
function Draw({rewardType,setRewardType,label,setLabel,spinning,winner,spin}:{rewardType:string;setRewardType:(v:string)=>void;label:string;setLabel:(v:string)=>void;spinning:boolean;winner:any;spin:()=>void}){return <><Title title="Reward Draw" sub="The admin starts the draw. The database selects a registered participant at random. Game points do not affect selection."/><Panel title="Start a secure random draw"><div className="grid gap-3 md:grid-cols-3"><select value={rewardType} onChange={e=>setRewardType(e.target.value)} disabled={spinning} className="rounded-xl border-2 border-slate-200 p-3"><option value="free_recharge">Free Recharge Card</option><option value="free_data">Free Data</option><option value="extra_food">Extra Plate of Food</option><option value="cash_prize">Cash Prize</option><option value="secret_gift">Secret Gift</option></select><input value={label} onChange={e=>setLabel(e.target.value)} disabled={spinning} placeholder="Reward description" className="rounded-xl border-2 border-slate-200 p-3"/><button onClick={spin} disabled={spinning||!label.trim()} className="rounded-xl bg-[#FFCC34] p-3 font-black text-[#003B63] disabled:opacity-50">{spinning?"DRAWING... 🎡":"START DRAW 🎉"}</button></div>{spinning&&<div className="mt-5 rounded-2xl bg-[#003B63] p-8 text-center text-white"><div className="mx-auto h-20 w-20 animate-spin rounded-full border-8 border-[#00B8E5] border-t-[#FFCC34]"/><p className="mt-4 font-black text-[#FFCC34]">THE WHEEL IS SPINNING...</p></div>}{winner&&!spinning&&<div className="mt-5 rounded-2xl bg-[#003B63] p-6 text-center text-white"><Sparkles className="mx-auto text-[#FFCC34]"/><p className="mt-2 text-xs font-black text-[#FFCC34]">WINNER</p><h3 className="text-3xl font-black">{winner.full_name}</h3><p>{winner.registration_no} • {winner.branch}</p><p className="mt-4 inline-block rounded-xl bg-white/10 px-5 py-3 font-black">{winner.reward_label}</p></div>}</Panel></>}
function Winners({data,claim}:{data:Data;claim:(id:string)=>void}){return <><Title title="Recent Winners" sub="Every win remains as a separate record."/><Panel title={`${data.recent_winners.length} recent reward records`}><WinTable rows={data.recent_winners} claim={claim}/></Panel></>}
function Claims({data,claim}:{data:Data;claim:(id:string)=>void}){const rows=data.recent_winners.filter(w=>w.claim_status==="pending");return <><Title title="Reward Claims" sub="Only authorized admins can mark an eligible reward as claimed."/><Panel title={`${rows.length} pending claims`}><WinTable rows={rows} claim={claim}/></Panel></>}
function WinTable({rows,claim}:{rows:Win[];claim:(id:string)=>void}){return rows.length===0?<Empty text="No reward records found."/>:<div className="overflow-x-auto"><table className="w-full min-w-[700px] text-sm"><thead><tr className="text-left text-[10px] uppercase tracking-wider text-slate-500"><th className="p-3">Winner</th><th className="p-3">Reward</th><th className="p-3">Payment</th><th className="p-3">Status</th><th className="p-3"/></tr></thead><tbody>{rows.map(w=><tr key={w.id} className="border-t border-slate-100"><td className="p-3"><b>{w.full_name}</b><br/><span className="text-slate-500">{w.registration_no} • {w.branch}</span></td><td className="p-3 font-bold">{w.reward_label}</td><td className="p-3">{w.paid?<span className="font-bold text-green-700">Verified</span>:"Pending"}</td><td className="p-3 font-bold">{w.claim_status}</td><td className="p-3">{w.claim_status==="pending"&&w.paid&&<button onClick={()=>claim(w.id)} className="rounded-lg bg-[#003B63] px-3 py-2 font-bold text-white">Mark Claimed</button>}</td></tr>)}</tbody></table></div>}
function Players({rows,search,setSearch,onPaid,paymentOnly=false}:{rows:Row[];search:string;setSearch:(v:string)=>void;onPaid:(c:string,v:boolean)=>void;paymentOnly?:boolean}){return <><Title title={paymentOnly?"Payment Verification":"Players"} sub="Player data comes from convention_registrations and game profiles in the existing production project."/><Panel title={`${rows.length} matching participants`}><div className="relative"><Search className="absolute left-3 top-3.5 text-slate-400" size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search name, EYF Code or branch" className="w-full rounded-xl border-2 border-slate-200 py-3 pl-10 pr-3 outline-none focus:border-[#00B8E5]"/></div><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[760px] text-sm"><thead><tr className="text-left text-[10px] uppercase tracking-wider text-slate-500"><th className="p-3">Code</th><th className="p-3">Name</th><th className="p-3">Branch</th><th className="p-3">Points</th><th className="p-3">Games</th><th className="p-3">Payment</th></tr></thead><tbody>{rows.map(r=><tr key={r.registration_no} className="border-t border-slate-100"><td className="p-3 font-bold">{r.registration_no}</td><td className="p-3 font-bold">{r.full_name}</td><td className="p-3 text-slate-500">{r.branch}</td><td className="p-3 font-black text-[#004F82]">{r.points}</td><td className="p-3">{r.games_played}</td><td className="p-3"><button onClick={()=>onPaid(r.registration_no,!r.paid)} className={`rounded-lg px-3 py-2 font-bold ${r.paid?"bg-green-100 text-green-800":"bg-slate-100 text-[#003B63]"}`}>{r.paid?<><CheckCircle2 size={15} className="mr-1 inline"/>Verified</>:"Mark Paid"}</button></td></tr>)}</tbody></table>{rows.length===0&&<Empty text="No matching participants."/>}</div></Panel></>}
function Leaderboard({rows}:{rows:Row[]}){return <><Title title="Points Leaderboard" sub="Sorted from convention_game_profiles: points descending."/><Panel title="Top players"><div className="overflow-x-auto"><table className="w-full min-w-[600px] text-left"><thead><tr className="text-[10px] uppercase tracking-wider text-slate-500"><th className="p-3">Rank</th><th className="p-3">Name</th><th className="p-3">Branch</th><th className="p-3 text-right">Points</th></tr></thead><tbody>{rows.slice().sort((a,b)=>b.points-a.points||a.full_name.localeCompare(b.full_name)).map((r,i)=><tr key={r.registration_no} className="border-t border-slate-100"><td className="p-3 font-black text-[#004F82]">{i<3?["🥇","🥈","🥉"][i]:i+1}</td><td className="p-3 font-bold text-[#003B63]">{r.full_name}</td><td className="p-3 text-slate-500">{r.branch}</td><td className="p-3 text-right font-black text-[#003B63]">{r.points}</td></tr>)}</tbody></table></div></Panel></>}
function Attendance({rows}:{rows:{day:string;checked_in:number}[]}){const labels=new Map([["2026-10-08","Day One — Thursday, October 8, 2026"],["2026-10-09","Day Two — Friday, October 9, 2026"],["2026-10-11","Day Three — Sunday, October 11, 2026"]]);return <><Title title="Attendance Overview" sub="Read-only view of the existing convention_checkins table."/><div className="grid gap-4 md:grid-cols-3">{["2026-10-08","2026-10-09","2026-10-11"].map(day=><div key={day} className="rounded-2xl bg-white p-5 shadow-sm"><ClipboardCheck className="text-[#00B8E5]"/><p className="mt-3 text-sm font-black text-[#003B63]">{labels.get(day)}</p><p className="mt-4 text-4xl font-black text-[#004F82]">{rows.find(r=>r.day===day)?.checked_in||0}</p><p className="text-xs font-bold uppercase tracking-wider text-slate-500">checked in</p></div>)}</div></>}
function Empty({text}:{text:string}){return <p className="rounded-xl bg-slate-50 p-5 text-center text-sm text-slate-500">{text}</p>}
